fix: drop volumes_parent_id_fkey constraint when modifying volumes.parent_id column
I was testing how idempotent the migration was and found that running
this query multiple times resulted in an error:

```
ERROR: could not find cast from 16430 to 3500
```

Figured out this is a bug in postgres. See this page for more details:
https://www.postgresql.org/message-id/20191116235657.4ratlshjd7dt3svw%40development
or search for "could not find cast from 3904 to 3831" to find the
original report.

Thankfully the volumes table is small so it doesn't cost much time to
drop and re-add the constraint. Running all three queries multiple times
within one transaction works as expected.

Signed-off-by: Taylor Silva <dev@taydev.net>